### PR TITLE
Added GitHub Action to check source file endings

### PR DESCRIPTION
**Pull request by blinkdog**
## What Does This PR Do
Adds a GitHub Action to check endings on source files.

Files ending with extensions `.dm` (DreamMaker code), `.dme` (DreamMaker environment), and `.dmm` (DreamMaker map) are checked to ensure they end with a Linux line ending (`\n`).

## Why It's Good For The Game
This PR does not affect the game. It adds some tooling to GitHub to perform checks on merges and pull requests.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Ok you already merged a copy of this in even though its completley redundant with the travis configuration, and now you have made the exact same PR, which somehow isnt merge conflicted because its already been merged in.

I am **trying** to offer support here, but since its blatantly going ignored, I think I will stop bothering.

**Comment by blinkdog** [comment]
> Ok you already merged a copy of this in even though its completley redundant with the travis configuration, and now you have made the exact same PR, which just changes the word `line` to `file`

This action is slightly different than #220 ...

#220 checks all the source files for the presence of Windows line endings.
#226 checks that all the source files end with a Linux newline.

The core operation (reduce over all source files) is the same, so I reused most of the code from the previous action but tweaked the reduction.

**Comment by AffectedArc07** [comment]
Mixing between line endings is a recipe for disaster, and again, travis already checks for newlines at the end of a file
https://github.com/ScorpioStation/ScorpioStation/blob/master/tools/travis/check_grep.sh#L27

**Comment by blinkdog** [comment]
>>#220 checks all the source files for the presence of Windows line endings.

> Mixing between line endings is a recipe for disaster, and again, travis already checks for newlines at the end of a file
> https://github.com/ScorpioStation/ScorpioStation/blob/master/tools/travis/check_grep.sh#L27

Apologies. I meant this to convey "the presence of (unwanted) Windows line endings", but in context with the description of the other check, my wording was confusing (at best). More accurately perhaps:

#220 checks that none of the source files contain any Windows line endings
#226 checks that all the source files end with a Linux newline

**Comment by AffectedArc07** [comment]
Checking for only linux line endings is fine, and so is checking for a trailing line at EOF. I just question the need to both these actions when travis already does both of these, and has done for 7 months.

**Comment by blinkdog** [comment]
>I just question the need to both these actions when travis already does both of these, and has done for 7 months.

You're right. Strictly speaking, these actions aren't necessary; the Travis CI integration will report the same information for a given commit to the repository.

Warning: This is where we cross into opinion and advocacy. I'll try to explain my goals; if your own goals are similar, there may be something of value here for you. If your goals are very different, then these PRs might not be worth your time. In no case, do I believe that we should or must have the same goals at all times; that's just silly.

I want to improve the CI of the repository and I think breaking CI tasks down into individual GitHub Actions is a good way to do this. My reasoning is:

1. GitHub Actions integrate directly with GitHub

By keeping to GitHub Actions, when an action fails there isn't a need to log into another site. I've observed when Travis CI fails, it's necessary to click through to the Travis site to discover why the check failed. In my opinion, the GitHub UI/UX for checks is faster and easier to use.

2. GitHub Actions are parallelizable

Each GitHub Action that doesn't depend on another action can be run on separate runners. With two actions, this isn't a big deal. With fifty or more, it could be significantly faster to allow each action to run in parallel. There is also the option of self-hosted runners if one really wants to apply CPU to the problem.

Note that the two actions that I've written recently could have been put together in one action; they iterate over files and don't need to change them at all. In the good old days, that's an opportunity to maximize throughput via cache-hit. These days, there are idle cores on standby waiting to devour the problem, and the more parallel you can make it, the better.

3. Small task-focused actions are more flexible

Lets say the repository eventually includes 50 actions. If someone wants to re-purpose a subset of them (say 5 to 10), it's pretty easy to grab the individual actions (and the corresponding tool subdirectories) and port them into another repository. Likewise, if somebody forks the repository and decides that Windows line endings are far superior to Linux line endings, disabling specific checks is fairly trivial and still allows them to retain all the actions they want to keep.

----

All of this said, Rome was not built in a day. These check actions are the start of adding CI improvements. I expect to write plenty more over time; some that will overlap Travis, some that will be novel, and some that will be utterly specific to ScorpioStation. I think investing effort in these small task-focused GitHub Actions will make them useful to us and to others in the future.

If you have feedback and/or ideas to improve this process, I'd love to hear it. Perhaps refactoring the Travis checks into GitHub Actions is an easy way to leverage the value you've created into better CI. I'd be willing to put in the refactoring effort if you're willing to answer questions about the Travis implementation when I get stuck.

**Comment by AffectedArc07** [comment]
Actions runs are not fully async, and you are limited to 20 concurrently. While that may seem like a lot, if youre breaking every step in travis down separately, thats not going to go extremely well, especially since some rely on previous scripts (EG: Compile all requires generate_maplist, unit test requires compile all and the SQL validation).

Also mass actions turns into this
image

Dont be TGS.

**Comment by blinkdog** [comment]
> Actions runs are not fully async, and you are limited to 20 concurrently. While that may seem like a lot, if youre breaking every step in travis down separately, thats not going to go extremely well, especially since some rely on previous scripts (EG: Compile all requires generate_maplist, unit test requires compile all and the SQL validation).

Agreed. Some problems are inherently serial; that's just the nature of the beast. You wrote the Travis integration, so I'm inclined to believe you that starting there and trying to break it into actions isn't a good plan.

That said, if I write an action that overlaps Travis, I won't lose too much sleep over it. We're still 13 actions away from filling all the concurrent slots. :smile:

**Comment by AffectedArc07** [comment]
I had started to turn the entire CI chain into actions but ran into issues, specifically with PHP stuff and GH actions not having phpenv. 



My main issue with this PR is you have 2 actions runs which need to setup and modify line endings with 2 coffeescript files and both need the same dependencies.


I really do ask "is the overhead of setting up an entire actions runner that's the exact same just for the sake of synchronicity worth it? When you could just run both scripts inside the same runner, and save on download times"

**Comment by blinkdog** [comment]
> My main issue with this PR is you have 2 actions runs which need to setup and modify line endings with 2 coffeescript files and both need the same dependencies.
> I really do ask "is the overhead of setting up an entire actions runner that's the exact same just for the sake of synchronicity worth it? When you could just run both scripts inside the same runner, and save on download times"

This is a good point; there is an opportunity to optimize.

I suppose it comes down to if these actions are worth taking independently.
Does it make sense to use or disable the actions independently?

The use cases that I've got are not my own use case:
- Someone wants Linux line endings but doesn't care about a trailing newline EOF
- Someone wants Windows line endings and does care about trailing newline EOFs
(note, this one works because a file ending in `\r\n` also ends with `\n`)

I'm starting to lean in favor of merging the two into a single action. :thinking:

**Pull request merged**
