### PR TITLE
Restore and shim the Cyberiad

### PR DESCRIPTION
**Pull request by blinkdog**
## What Does This PR Do
Restores the BoxStation (Cyberiad) map to the codebase.
Some entities are shimmed until they can be harmonized with upstream.

## Why It's Good For The Game
Allows upstream changes to Cyberiad to apply to Cyberiad on upstream merges instead of git "helping" them apply to Emerald.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I am still going to question the entire reason for gutting Travis and the standard TGUI deployment features among other things in favour of docker, especially since this locks you out of hosting on a platform such as TGS4, requiring docker to be used, which also locks out remote administration of the server outside of a host perspective.

It really does confuse me.

**Comment by blinkdog** [comment]
> I am still going to question the entire reason for gutting Travis and the standard TGUI deployment features among other things in favour of docker, especially since this locks you out of hosting on a platform such as TGS4, requiring docker to be used, which also locks out remote administration of the server outside of a host perspective.

@AffectedArc07 that's a lot of ground to cover: TGUI, Travis, Docker, TGS, remote administration. Each of them with design considerations and my answers will probably lead to follow-up questions. Would you like to "talk shop" on Discord? Or is there a specific question you'd like to start with here?

**Comment by AffectedArc07** [comment]
- TGUI: I dont see why the compiled `tgui.bundle.js` was taken out of the repo given the extra steps needed for a continuous deployment to keep a remote copy up to date, and having clients download it if they want to run the codebase
- Travis: You mentioned this before, and I can kind of see the reason for migrating to GitHub actions (I attempted to do that before, but gave up because of trashy phpenv support)
- Docker: Every experience I have had with docker has always ended negatively, and theres a reason its rarely, if ever used for production SS13 hosting, for numerous reasons (EG: Docker windows has the virtualization overhead which cripples BYOND, and not every server is fully linux compliant [Paracode wasnt for a long time])
- TGS + Remote administration: I swear you lot made a push before to get your code running on TGS so your admins and other people could hard restart the server if needed, not to mention the other great flexibilities TGS offers, so this seems like a step back, no?

My main question with all of this is just "why", when the existing systems work fine, and very efficiently.

**Comment by blinkdog** [comment]
> My main question with all of this is just "why", when the existing systems work fine, and very efficiently.

Let's see if I can answer the "why" question inline. If you have any follow-ups, just ask.

> TGUI: I dont see why the compiled `tgui.bundle.js` was taken out of the repo given the extra steps needed for a continuous deployment to keep a remote copy up to date, and having clients download it if they want to run the codebase

This is due to downstream use-case. At some point, Scorpio will implement a custom TGUI interface for something and then we will be unable to rely on the upstream build for TGUI. (Note: This is _expected_, it's not upstream's responsibility to build our custom stuff.)

At that point, effort must be spent to manage it within the tree. Being downstream, that management will fall to me; and subtract from the time that I have available to work on other things. ~~If~~ When I mess up, because that's what humans do, the production server runs with the wrong stuff, developers have trouble with wrong stuff, or both. All of this becomes additional troubleshooting time, subtracting from the time that I have available to work on other things.

Keeping it out of the tree ensures the wrong thing is never there by mistake. Nobody can download an outdated or mismatched copy as part of the source tree, because that copy doesn't exist. The production image uses a fresh build from the source. Contributors can be helped with "See the script called `prepare-dev-windows.bat`? Double click that."

Moreover, the TGUI bundle is added to .gitignore. A contributor would have to work pretty damn hard to accidentally put a conflicting version of the TGUI bundle into their PR, no matter how many times they do or don't run the script to update their local copy. This prevents TGUI related merge conflicts in the PR and enables a smoother contribution process with less hassle for both the contributor and the maintainer. Yet, if they do make TGUI changes, those will always be vetted to at least build correctly.

In essence, this ensures our maintenance effort for TGUI is basically nil. The approach saves time and effort on multiple fronts, but it comes with its own price...
 
> Travis: You mentioned this before, and I can kind of see the reason for migrating to GitHub actions (I attempted to do that before, but gave up because of trashy phpenv support)

... remember that price I talked about? The DMB build expects a TGUI bundle as input to the build process. Travis is written to expect that TGUI bundle is coming from the source tree. Removing it permanently broke Travis integration. Loss of this excellent CI tool meant more time and effort spent hunting down the bugs that it would have caught and prevented. So migration to GitHub actions, shifted from Q4 (neither urgent nor important) into Q1 (both urgent and important).

Ultimately, I didn't bring over everything from Travis. The PHP stuff was not migrated, neither was the SQL stuff.
It was a judgment call, and eventually I decided those things didn't need to be migrated at this time.
 
However, there were a few upsides to the GitHub CI migration:
* The GitHub CI code checker found unmanaged globals in [browserOutput.dm](https://github.com/ParadiseSS13/Paradise/blob/master/goon/code/datums/browserOutput.dm)
* The GitHub CI Dreamchecker found the issue that I PR'd in Paradise #14631
* The GitHub CI Dreamchecker found some relative pathing in [code/modules/mob/typing_indicator.dm](https://github.com/ScorpioStation/ScorpioStation/pull/249/commits/8707c626e2b6a1d96fa0d9f79c7a0ae870daa36b)

The unmanaged globals I didn't PR, because [my solution to fix it](https://github.com/ScorpioStation/ScorpioStation/commit/732276276390f81273c7189fb87ebc0d1215e3fe) still needs review. If you've got a spare moment to look it over, I'd appreciate that a lot.

> TGS + Remote administration: I swear you lot made a push before to get your code running on TGS so your admins and other people could hard restart the server if needed, not to mention the other great flexibilities TGS offers, so this seems like a step back, no?

I'm going to answer TGS first and then Docker because the context will make more sense that way.

Yes, I put some effort into hosting with TGS. There were some benefits to using TGS for hosting:
* Automatically deploying the latest build from `master` on GitHub
* Being able to selectively testmerge PRs for deployment

There were also some drawbacks. It's not clear to me that these were not my own fault, possibly due to misconfiguration, misuse, running on Linux instead of Windows, or some other cause. So, I'll avoid throwing shade at TGS. A lot of people swear by it, and more power to them.

For Scorpio, I have a custom hosting solution that meets my requirements well and that I am quite happy with.

> Docker: Every experience I have had with docker has always ended negatively, and theres a reason its rarely, if ever used for production SS13 hosting, for numerous reasons (EG: Docker windows has the virtualization overhead which cripples BYOND, and not every server is fully linux compliant [Paracode wasnt for a long time])

Sorry to hear that your experiences with Docker have been so negative. I agree that the state of Docker on Windows is absolutely horrible; I wouldn't mess around with it on that platform either. (Thanks for enlightening me, by the way.)

Scorpio uses Docker for production SS13 hosting. I have no complaints.

**Comment by AffectedArc07** [comment]
> This is due to downstream use-case. At some point, Scorpio will implement a custom TGUI interface for something and then we will be unable to rely on the upstream build for TGUI. (Note: This is _expected_, it's not upstream's responsibility to build our custom stuff.)

You already did with the canvases, however, this isnt a major issue. You do an upstream merge, PR, and just run `cd tgui && bin/tgui` to build TGUI with all UIs (yours + upstream), and that resolves the conflict very quickly. I can see your reasoning for other things though.

**Pull request merged**
