### PR TITLE
Adds Lesser Jump to Skrell

### PR DESCRIPTION
**Pull request by ZomgPonies**
## What Does This PR Do
Gives Skrell a Lesser Jump ability (innate)

To compare it with the Jump mutation it is:
6 tiles instead of 10
10 seconds cooldown instead of 6

## Why It's Good For The Game
Going through every species and giving them a something flavourful and thematic is an important part of differentiating them.

## Changelog
:cl:
add: Adds Lesser Jump to Skrell
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Aren't skrell more squids than frogs? Not sure if this really fits them, honestly.

**Comment by ZomgPonies** [comment]
Think of them as "generic amphibian species". Since we don't have any underwater stuff, this is the closest I've gotten to given that something somewhat flavourful.

**Comment by McRamon** [comment]
Well i dunno, beast races feel more appropriate for the jump ability. Skrell dont look like they have strong legs to perform inhuman jumps. When i think about skrells, i feel like on land, outside of their natural sea environment of their homeworld, they would be in fact one of the weakest race, on the ipc level, without any big ability. Hell, they even make sense to require some sort of internals like voxes do. 
Maybe we could think outside of the box and give skrells not the ability But rather some different feature, for example unique loadout items.

**Comment by McRamon** [comment]
Or unique skrell only job, barber style fluff job (or civillian title)

**Comment by ZomgPonies** [comment]
I don't like this, I'll find something else.

**Pull request closed without merging**
