### PR TITLE
Remove Vox is Pox Graffiti

### PR DESCRIPTION
**Pull request by blinkdog**
## What Does This PR Do
Removes Vox is Pox from the list of draw/spray graffiti.
Decal still exists in the game for admeme'ery.

## Why It's Good For The Game
Quoting from The First Book of the Silent Father:
`...`

## Changelog
:cl:
del: Removed Vox is Pox Graffiti
/:cl:

### CODE REVIEW

**Comment by EmeraldCandy** [comment]
why though?

**Comment by Spacemanspark** [comment]
Some people aren't able to take a joke towards a fictional race in a video game.

I could go on a hilarious rant about the whole thing, but it's not really my place.
I would advise against removing the graffiti from player hands, however.

**Comment by Cocacolagua** [comment]
y

**Comment by Kiyahitayika** [comment]
Calling myself out as the person who raised this. However, I don't think this is the way to go about ... this.

Looking at graffiti, it isn't used that often. When it is used, the only options are ... dumb. They're fictional slurs or anti-security or whatever. They're just weird. At this point, I'd rather take a step back and see how we could change graffiti.

If ArkSoft is more inclusive of other species, I'd understand removing this sprite from a lore/RP perspective, but then isn't that removing RP gimmicks? And, then, why not remove other graffiti sprites? We have a sort of arts and crafts room on the ARS Scorpius and probably more can be done in terms of Graffiti.

**Comment by blinkdog** [comment]
> Calling myself out as the person who raised this. However, I _**no longer**_ think this is the way to go about ... this.

I'm in favor of more graffiti. Let's do that on another PR.

**Pull request closed without merging**
