### PR TITLE
Changed some NT Branding to Arksoft.

### PR DESCRIPTION
**Pull request by Vi-sz**
## What Does This PR Do
Changes Nanotrasen branding to Arksoft on various items.

## Why It's Good For The Game
Company consistency.

## Images of changes

box_ert
cardboard_ark_representative
cardboard_blueshield
cardboard_hop
cardboard_internal_affairs
cardboard_magistrate
decks_nanotrasen
nt_hoodie
nt_hoodie_hood
ntsecure
ntsecure1
ntsecurebroken
ntsecureoff
paperbag_nanostrasen
poster2_legit
sheetcaptain
sheetcentcom
singlecard_down_nanotrasen
soapnt
sop
sop_cargo+science
sop_command+security
sop_legal+engineering
sop_service+medical
us_shirt_nano_s

## Changelog
:cl:
tweak: 

`icons\mob\suit\nt_hoodie`
`icons\mob\suit\nt_hoodie_up`
`icons\mob\underwear\us_shirt_nano_s`

`icons\obj\closet\ntsecure`
`icons\obj\closet\ntsecure1`
`icons\obj\closet\ntsecurebroken`
`icons\obj\closet\ntsecureoff`

`icons\obj\contraband\poster2_legit`

`icons\obj\items\sheetcaptain`
`icons\obj\items\sheetcentcom`
`icons\obj\items\soapnt`

`icons\obj\library\sop`
`icons\obj\library\sop_command`
`icons\obj\library\sop_security`
`icons\obj\library\sop_legal`
`icons\obj\library\sop_engineering`
`icons\obj\library\sop_service`
`icons\obj\library\sop_medical`
`icons\obj\library\sop_cargo`
`icons\obj\library\sop_science`

`icons\obj\storage\paperbag_NanotrasenStandard`
`icons\obj\storage\paperbag_NanotrasenStandard_closed`
`icons\obj\storage\box_ert`

`icons\obj\toy\deck_nanotrasen_full`
`icons\obj\toy\deck_nanotrasen_half`
`icons\obj\toy\deck_nanotrasen_low`
`icons\obj\toy\deck_nanotrasen_empty`
`icons\obj\toy\singlecard_down_nanotrasen`

`icons\obj\cardboard_boxes\cardboard_hop`
`icons\obj\cardboard_boxes\cardboard_ark_representative`
`icons\obj\cardboard_boxes\cardboard_open_ark_representative`
`icons\obj\cardboard_boxes\cardboard_blueshield`
`icons\obj\cardboard_boxes\cardboard_open_blueshield`
`icons\obj\cardboard_boxes\cardboard_internal_affairs_agent`
`icons\obj\cardboard_boxes\cardboard_open_internal_affairs_agent`
`icons\obj\cardboard_boxes\bardboard_magistrate`

/:cl:

### CODE REVIEW

**Comment by trololiver112** [comment]
Do you think you could change the paths too? makes it easier to recognize in the future and stuff. example would be `nt_hoodie` to something like `ark_hoodie`

You should be able to do this quite easily with the search and replace tool if you write the exact path down in it

**Comment by blinkdog** [comment]
> Do you think you could change the paths too? makes it easier to recognize in the future and stuff. example would be `nt_hoodie` to something like `ark_hoodie`
> 
> You should be able to do this quite easily with the search and replace tool if you write the exact path down in it

Actually, @Vi-sz and I were talked about that on Discord, and I encouraged them to post up the sprites without any path changes. Sorry, that one's on me!

I'm actually hoping to blow the dust off an old tool that I wrote, and rework it a little bit to give us some leverage on icon conflicts/merges.

**Comment by blinkdog** [comment]
@Vi-sz Sorry that this has been sitting for awhile. I've been swamped a bit. I'll make it a point to get this merged this coming weekend.

**Comment by Vi-sz** [comment]
@blinkdog Pff, no worries. I've been a bit MIA with things recently. Merge as see fit!

**Pull request merged**
