### PR TITLE
PDA Sprite Support

### PR DESCRIPTION
**Pull request by Kiyahitayika**
## What Does This PR Do

- Resolves https://github.com/ScorpioStation/ScorpioStation/issues/308
- Adds code support for PDA App Overlays
- Rotates your ID for Science!

## Why It's Good For The Game

- ID in middle of PDA looks funky
- Supports Spriters with Coding

## Images of changes
image
No ID:
image
Yes ID:
image

## Changelog
:cl:
tweak: Rotates the in-PDA IDs for Science! And all everyone else, too.
/:cl:

### CODE REVIEW

**Comment by blinkdog** [comment]
@Kiyahitayika Is this one ready for merging, or is there more work to be done yet?

**Comment by Kiyahitayika** [comment]
> @Kiyahitayika Is this one ready for merging, or is there more work to be done yet?

This should be ready.

**Comment by Kiyahitayika** [comment]
@blinkdog Hey, I was just speaking to @AffectedArc07 about why Goon code/material is in separate folders and files. I thought Goon had AGPL3, but they actually have CC. I changed the file path and name for the ID overlays in this PR, we should likely want to change them back to where they were.

**Comment by blinkdog** [comment]
> @blinkdog Hey, I was just speaking to @AffectedArc07 about why Goon code/material is in separate folders and files. I thought Goon had AGPL3, but they actually have CC. I changed the file path and name for the ID overlays in this PR, we should likely want to change them back to where they were.

Ahhh, good catch. Can you open an issue for that and reference this one (#312) ?

**Pull request merged**
