### PR TITLE
Paradise upstream merge

### PR DESCRIPTION
**Pull request by ZomgPonies**
## What Does This PR Do
Merges everything upstream up until now, including a LOT of bugfixes, some optimizations, the beginnings of the tgui conversion and the removal of zombies.

## Why It's Good For The Game
Bugfixes and optimizations, while providing better UI options is definitely in our interest. Also staying close to upstream/master until we have a big enough team of dedicated coders to start really cherry-picking what we want to port is kinda needed at this point in the project. Individual controversial features can be reverted by seperate PRs on our end.

## Changelog
:cl:
add: Upstream merge from Paradise
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
...Does scorpio even have access to the engineering outpost?
If it does, this PR will likely break a few things.

**Comment by Spacemanspark** [comment]
I also think arc said something about TGUI needing to be built from the ground up

**Comment by trololiver112** [comment]
We would need our own map changes for that probably yeah, and to he honest I feel that PR could be brought up to discussion anyways

**Comment by AffectedArc07** [comment]
image
image
image
Good luck to whichever poor sod reviews this

**Comment by Spacemanspark** [comment]
Oh lord does this notify all of those poor people

**Comment by ZomgPonies** [comment]
Yes it's a shitshow, I assumed Scorpio still had an engineering outpost so left it in, and there's a specific runtime I spent literal hours yesterday trying to fix to no avail.

**Comment by ZomgPonies** [comment]
`[2020-07-06T00:58:33] Runtime in code/modules/space_management/zlevel_manager.dm,52: Non-existent z level: 'CentComm'

[2020-07-06T00:58:33] Runtime in level_traits.dm,63: Cannot read null.zpos

  proc name: level name to num (/proc/level_name_to_num)

  src: null

  call stack:

  level name to num("CentComm")

  Blackbox Recorder (/obj/machinery/blackbox_recorder): Destroy(0)

  qdel(Blackbox Recorder (/obj/machinery/blackbox_recorder), 0)

  Blackbox Recorder (/obj/machinery/blackbox_recorder): New(the floor (96,119,2) (/turf/unsimulated/floor))`

Spent hours working on this, couldn't find any difference with cyberiad. Any help would be appreciated.

**Comment by ZomgPonies** [comment]
Ok I'm a little further along. That runtime happens only once at server initialization, and looking at the MC datum information on the main server, Centcomm gets loaded in properly later.

**Comment by ZomgPonies** [comment]
PS: Do not map a second blackbox on the Centcomm Z-level, ever. If the one on station gets destroyed it gets automatically re-created at Centcom.

**Comment by AffectedArc07** [comment]
I fixed that at para before. The issue seems to be that your zlevel definitions werent correct. `Non-existent z level: 'CentComm'`

**Comment by ZomgPonies** [comment]
Should be ready for merge.

**Pull request merged**
