### PR TITLE
Ports runechat from SS220 - Attempt #2

### PR DESCRIPTION
**Pull request by ZomgPonies**
## What Does This PR Do
Port from https://github.com/RV666/Paradise/commit/158f328e54289b2b82ee640e9094ab49e6060b4d thanks russkies!

Adds Runechat, which can be disabled via Game Preferences menu if you don't want to use it, along with a few other options for it.

**THIS REQUIRES IMPORTING THE runechat.sql FILE IN ORDER TO MODIFY THE DB SCHEMA TO ALLOW SAVING THOSE PREFERENCES.**

## Why It's Good For The Game
Having tried it on many other popular servers with >100 populations, I found it wasn't too 'busy' on screen even in high-talk areas like the bar, and added a lot in order to easily see who said what and react quicker to text chat.

## Images of changes
Capture

## Changelog
:cl:
add: Added Runechat
/:cl:

### CODE REVIEW

**Comment by Tokorizo** [comment]
any update on this? would love to see it added to the server

**Comment by ZomgPonies** [comment]
- Megaphones should be +1 size, currently not showing in runechat
- Whispers are supposed to be -1 size, currently same as talk (but also show radio symbol)
- Talking in radio shows both the radio icon and message (normal talk size), and the regular speech message (+1 size)
- Set colors based on language used

**Comment by ZomgPonies** [comment]
Spent many hours on this, fixed the double-speak when using radio (at least for the speaker, didn't have anyone to test against).
Languages are handled at a way way way previous level that's going to be a bitch to bring back down to hearsay.dm


Megaphone should be an easy fix I'll do tomorrow.

**Comment by ZomgPonies** [comment]
Test #2 results:

- A couple of instances of </spans> showing up when they shouldn't. Rarely happens, haven't pinpointed exact conditions yet.
- SOMEHOW (actual magic) clownish actually changes color for the maptext. Need to investigate, could be a shortcut to adding colors to ALL languages!
- AI hologram cannot see maptext OR be seen when he talks -- Needs to be fixed before merge.

**Comment by ZomgPonies** [comment]
I believe this is ready for final test and mege, it's in good enough shape for production.

**Comment by Spacemanspark** [comment]
Checks failed?

**Comment by trololiver112** [comment]
Checks have some issues but it shouldn’t be conflicted.

**Pull request merged**
