### PR TITLE
Add time limit for Cyborg to select Security module

### PR DESCRIPTION
**Pull request by blinkdog**
## What Does This PR Do
Adds a five minute time limit for a Cyborg to select the Security module.

If they do not select the Security module within the time limit, it disappears from the list and is no longer available for selection.

Using a Reset Module to reset the Cyborg will remove a previously selected module and reset the timer; a reset Cyborg will again have five minutes to select the Security module.

## Why It's Good For The Game
During a round, a Traitor was attempting to complete their objective by stealing the CMO's locker.
A Cyborg that had not chosen a module witnessed the theft and selected the Security module.
The Cyborg then began to pursue/arrest the Traitor for the theft.

The Traitor sent me an adminhelp asking if the Cyborg was allowed to valid hunt using this method, that is reserve a module choice until witnessing a crime, and then become a Security borg.

In my opinion, this action does not violate the letter of the rules. The Cyborg did not interfere with the Traitor until it had chosen the Security module. After choosing the Security module, its job was to arrest Traitors in accordance with its lawset. The Cyborg appeared to be following its laws properly.

However, it did raise a question for me if this situation violated the spirit of the valid hunting rules.

**Should Cyborgs be required to pick the Security module sooner rather than later if they intend to apprehend Traitors?**
or
**Should Traitors beware that uncommitted Cyborgs are dangerous precisely because they can go Security on you in a heartbeat?**

This PR adds a time limit for the Cyborg to choose the Security module.
A Cyborg has five minutes to choose it or lose the option to choose Security.

## Changelog
:cl:
add: Cyborg now has a time limit to select the Security module
/:cl:

### CODE REVIEW

**Comment by MRgaty** [comment]
I dont see a problem with deciding your module based in an immediate situation, this will just be an inconsistent hassle.

**Comment by trololiver112** [comment]
Thinking about it. A borg should be able to choose a module base upon what is needed imo. A borg hears about a breach. Go engineering. A virus is killing the entire crew? Go medical. Slaughter demon? **JANITORIAL**. And considering it can not reset itself I don’t think this would be an issue.

However on another similar topic. Sec borgs are already a problem in themselves, and it’s my honest opinion that they should either be ERT only. Or limited to one at a time, with the exception of a malf upgrade maybe.

Giving this a 👎 only because i don’t think it is the right fix. Though i 100 percent agree with the direction

**Comment by trololiver112** [comment]
This does kinda remove a borgs ability to respond to the threat with a module accordingly, if the problem is a security issue.

Personally i think the issue lies in the security borg module itself, and Ithink that is what needs nerfing. Something like making it ERT only or limiting it to 1 at the time.

Overall neutral to the change, though i think it could be solved differently

**Comment by Spacemanspark** [comment]
Didn't we merge Kyet's changes that limited the slots to two sec borgs?

**Comment by ZomgPonies** [comment]
Could have been in the last upstream merge -- If so, I think that's enough to resolve the problem for now.

**Comment by nok-ko** [comment]
> Arrest Traitors according to its lawset

Wait, does a borg's module determine its job/directive? If so, this should be made more clear in-game.

**Comment by Spacemanspark** [comment]
@nok-ko not really, no.

**Comment by blinkdog** [comment]
Given that we merged Kyet's security cyborg limit and this solution has received mixed reviews, I'm going to close the PR.
We can revisit this if Security Cyborgs become or continue to be an issue.

**Pull request closed without merging**
