### PR TITLE
Botany Labeling Port from /tg/

### PR DESCRIPTION
**Pull request by Kiyahitayika**
## What Does This PR Do
- Resolves https://github.com/ScorpioStation/ScorpioStation/issues/338
- Ports https://github.com/tgstation/tgstation/pull/45914 by **cacogen** from /tg/ 

## Why It's Good For The Game
- Requested by players
- It's useful for Botanists
- I hecked around with it and was pretty pleased with the versatility of it. Also, it can help other players know at a glance whether you're getting a plant/produce item that is different from another plant/produce item.
- Consolidates some .dm files

**From the original PR:**
- Useful for genetically modified plants that can be easily confused with other plants of the same species.
- Useful for knowing which tray contains what by examining/shift-clicking the tray.
- Because plants can be renamed at the seed, you don't have to rename produce with different traits one by one to differentiate it. 
- Renamed produce items no longer occupy the same stack in Smartfridge (not sure if they did this currently on Paracode, but hey!)

## Images of changes

https://user-images.githubusercontent.com/69871346/108140906-b0475b00-7090-11eb-9096-395616cf4e5a.mp4

https://user-images.githubusercontent.com/69871346/108140915-b3dae200-7090-11eb-952a-ff1f2b156a32.mp4

## Changelog
:cl:
add: Seed name, seed description, and product description labeling with pen use on the seeds packet. This information carries over to the hydroponic tray, the plant, the harvested produce, and any seeds made from said produce.
/:cl:

### CODE REVIEW

**Comment by Kiyahitayika** [comment]
image
Hear me out - apples are now called Apple Trees.

**Comment by Kiyahitayika** [comment]
Fixed: 
image

**Comment by blinkdog** [comment]
@Kiyahitayika Is this one ready to be merged? Or are additional changes still pending?

**Comment by Kiyahitayika** [comment]
> @Kiyahitayika Is this one ready to be merged? Or are additional changes still pending?

I think everything is all set. I made sure that the product name is correctly derived. If you want to do a review, please feel free.  The code is directly ported with some tweaks for cleanliness.

**Pull request merged**
