### PR TITLE
8/9/20 Upstream Merge

### PR DESCRIPTION
**Pull request by ZomgPonies**
## What Does This PR Do
Paracode upstream merge

### CODE REVIEW

**Comment by blinkdog** [comment]
It looks like the merge squashed a few icon states:

ERROR: Missing icon_state: 'arkrep' in icons/obj/clothing/hats.dmi
ERROR: Missing icon_state: 'arkrep' in icons/obj/clothing/suits.dmi
ERROR: Missing icon_state: 'ark_hoodie' in icons/obj/clothing/suits.dmi

What procedure are you using to deconflict these?

**Comment by ZomgPonies** [comment]
Should be good now. Going to review my procedure for dmi conflicts so ensure I'm not missing anything.

**Comment by blinkdog** [comment]
Need to repair a few more icons, and then we should be ready to merge.

ERROR: Missing icon_state: 'arkrep' in icons/mob/head.dmi
ERROR: Missing icon_state: 'hudarksoftrepresentative' in icons/mob/hud.dmi
ERROR: Missing icon_state: 'hudbouncer' in icons/mob/hud.dmi
ERROR: Missing icon_state: 'arkrep' in icons/mob/suit.dmi
ERROR: Missing icon_state: 'arkrep_open' in icons/mob/suit.dmi
ERROR: Missing icon_state: 'ark_hoodie' in icons/mob/suit.dmi
ERROR: Missing icon_state: 'ark_hoodie_hood' in icons/mob/suit.dmi

**Comment by ZomgPonies** [comment]
Alright should be ready to go now.

**Pull request merged**
