### PR TITLE
Tweak Gamemode Configuration Weights

### PR DESCRIPTION
**Pull request by blinkdog**
**NOTE:** This affects an example configuration file; the configuration values on the server are set to these values, but not actually controlled by this PR. **This PR exists for discussion purposes.**

## What Does This PR Do
Tweaks the configured weights for the game mode selection. These numbers depend on population:

**Population: < 20**
GAMEMODE | WEIGHT | % PROBABILITY
-- | -- | --
EXTENDED | 3 | 100%

**Population 20-24**
GAMEMODE | WEIGHT | % PROBABILITY
-- | -- | --
EXTEND-A-TRAITORMONGOUS | 5 | 62.50%
EXTENDED | 3 | 37.50%

**Population 25-29**
GAMEMODE | WEIGHT | % PROBABILITY
-- | -- | --
CHANGELING | 5 | 27.78%
EXTEND-A-TRAITORMONGOUS | 5 | 27.78%
EXTENDED | 3 | 16.67%
VAMPIRE | 5 | 27.78%

**Population 30-39**
GAMEMODE | WEIGHT | % PROBABILITY
-- | -- | --
CHANGELING | 5 | 17.86%
EXTEND-A-TRAITORMONGOUS | 5 | 17.86%
EXTENDED | 3 | 10.71%
TRAITORCHAN | 5 | 17.86%
TRAITORVAMP | 5 | 17.86%
VAMPIRE | 5 | 17.86%

**Population 40+**
GAMEMODE | WEIGHT | % PROBABILITY
-- | -- | --
BLOB | 10 | 12.35%
CHANGELING | 5 | 6.17%
CULT | 10 | 12.35%
EXTEND-A-TRAITORMONGOUS | 5 | 6.17%
EXTENDED | 3 | 3.70%
NUCLEAR | 10 | 12.35%
REVOLUTION | 10 | 12.35%
SHADOWLING | 3 | 3.70%
TRAITORCHAN | 5 | 6.17%
TRAITORVAMP | 5 | 6.17%
VAMPIRE | 5 | 6.17%
WIZARD | 10 | 12.35%

## Why It's Good For The Game
Game modes that scale with server population is nice.

## Changelog
:cl:
tweak: Modified the game mode weights
/:cl:

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Keep in mind even with these chances and our current player peaks, you WILL see tons of extended because of low-pop, and maybe a couple of traitor rounds a night during peak hours if you're lucky. As our base numbers grow, you'll see more traitor rounds and maybe a few vamp or ling rounds, etc.

Once we get to some really decent steady population numbers, we'll be able to revisit the numbers and adjust them again based on what people want to see more of and what people want to see less of.

**Comment by ClockworkGolem** [comment]
This is a good change. I'd like to suggest taking it further and tying gamemode thresholds to the staffing of the Command and Security jobs, rather than the raw server population. I've seen 10-20 person rounds with multiple security personnel (who were therefore bored with nothing to do), and I've seen >20 pop rounds where there were few/zero Security or Command staff to deal with antagonists.

I don't know if a framework for triggering off specific department populations is in place, so this might be a big hassle. But if it does exist, perhaps it could be used to weight events as well. For examples: if there's a Chaplain make Vampires and Cults more likely, if there's a Detective make Traitor more likely, if there's a ton of security folks make Blob or Nuke Ops more likely, if there's loads of Command staff make revolutions more likely, etc.

**Comment by trololiver112** [comment]
Personally i feel some of the 10 weight options aren’t optimal. Having wizard, blob, nuclear and revolution take up 50% of the rounds on 40+ means a lot of chaos rounds that many might not enjoy.
There are many times when you load in to a round and you just want to play, that the shouting of  BLOB!!!11! or WIZZZZZARD on the radio or the war alert really gives you a “ah, no reason to do anything since the round will just randomly end”. Not to mention the issues with revolution before the re-do. I would lower the weight of those 4. And definitely blob, because god damn blob rounds, almost better if they were only a mid round but that’s another topic

**Comment by ZomgPonies** [comment]
The reason it's so high is because with current pop we're so unlikely to ever hit the numbers where they have a chance of triggering that you kinda WANT one of those gamemodes at that time. As our population grows and we hit 40+ more consistently, those numbers will get lowered back down.

**Comment by trololiver112** [comment]
Alright, but if we ever start to consistently hit those numbers i think we should consider tuning them down again. Because yeah 50% of the games as chaos only games is quite a lot

**Comment by blinkdog** [comment]
As noted, this PR existed only for discussion purposes. I think it can be closed now.

**Pull request closed without merging**
